web/routes.py
import os
import requests
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify
from models import Cafe, User
from models.database import db
from web.forms import RegisterForm, LoginForm, CafeForm
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.exc import IntegrityError
from flask_login import (
    login_user,
    login_required,
    logout_user,
)
from dotenv import load_dotenv
from pathlib import Path
from extensions import gmaps_client
from web.utils.decorators import admin_required

web_blueprint = Blueprint('web', __name__, template_folder='templates')

ENV_PATH = Path("..", "..", ".env")
load_dotenv(dotenv_path=ENV_PATH)


# Context processor to inject the MAPS_API_KEY into all templates
@web_blueprint.app_context_processor
def inject_maps_key():
    maps_api_key = os.getenv('MAPS_API_KEY')
    return dict(MAPS_API_KEY=maps_api_key)


@web_blueprint.route("/config")
def config():
    return jsonify({"mapsApiKey": os.getenv('MAPS_API_KEY', 'defaultKey')})


@web_blueprint.route("/")
def home():
    """Displays the home page with a list of cafes."""
    # Fetch all cafes from the database
    cafes = db.session.execute(db.select(Cafe)).scalars().all()
    return render_template("home.html", cafes=cafes)


@web_blueprint.route("/register", methods=["GET", "POST"])
def register():
    """Handles user registration.

    GET: Displays the registration form.
    POST: Processes the submitted form. Registers a new user if validation succeeds and the email is not already taken.
    Redirects to the index page upon successful registration or back to the register form with validation errors.

    Returns:
        Response: The register template on GET or redirect on successful POST.
    """
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            email = form.email.data
            name = form.name.data
            password = form.password.data
            password2 = form.password2.data
            if password != password2:
                flash('Passwords do not match.', 'danger')
                return redirect(url_for('web.register'))
            hashed_password = generate_password_hash(
                password, method='pbkdf2:sha256', salt_length=8
            )
            new_user = User(email=email, name=name, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('web.home'))
        except IntegrityError:
            db.session.rollback()
            flash("That email already exists, please login.", category='error')
            return redirect(url_for('web.login'))
    return render_template("register.html", form=form)


@web_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Handles user login.

    GET: Displays the login form.
    POST: Processes the submitted form. Logs in the user if validation succeeds and the email and password match.
    Redirects to the index page upon successful login or back to the login form with validation errors.

    Returns:
        Response: The login template on GET or redirect on successful POST.
    """
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = db.session.query(User).filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('web.home'))
        flash('Invalid email or password.', 'danger')
    return render_template("login.html", form=form)


@web_blueprint.route('/logout')
@login_required
def logout():
    """Logs out the current user and redirects to the index page.

    Returns:
        Response: Redirect to the index page.
    """
    logout_user()
    flash("You have been logged out.", category='success')
    return redirect(url_for('web.home'))


def construct_full_address(form):
    """
    Constructs a full address string from the given form data.

    Args:
        form: The form object containing the address input fields.

    Returns:
        A string representing the full address, with empty parts filtered out.
    """
    address_parts = [
        form.location_input.data,
        form.address2_input.data if form.address2_input.data else "",
        form.locality_input.data,
        form.administrative_area_level_1_input.data,
        form.postal_code_input.data,
        form.country_input.data,
    ]
    return ", ".join(filter(None, address_parts))


def get_geocode(address):
    """
    Get the latitude and longitude coordinates for a given address.

    Parameters:
    address (str): The address to geocode.

    Returns:
    tuple: A tuple containing the latitude and longitude coordinates.
           If the geocoding fails, returns (None, None).
    """
    try:
        geocode_result = gmaps_client.geocode(address)
        latitude = geocode_result[0]['geometry']['location']['lat']
        longitude = geocode_result[0]['geometry']['location']['lng']
        return latitude, longitude
    except (IndexError, requests.exceptions.RequestException) as e:
        return None, None


def cafe_exists(address):
    """
    Check if a cafe with the given address exists in the database.

    Args:
        address (str): The address of the cafe to check.

    Returns:
        bool: True if a cafe with the given address exists, False otherwise.
    """
    return Cafe.query.filter_by(location=address).first() is not None


def create_cafe(form, address, lat, lng):
    """
    Create a new Cafe object based on the provided form data, address, latitude, and longitude.

    Args:
        form (Form): The form data containing the cafe details.
        address (str): The address of the cafe.
        lat (float): The latitude of the cafe's location.
        lng (float): The longitude of the cafe's location.

    Returns:
        Cafe: The newly created Cafe object.
    """
    return Cafe(
        name=form.name.data,
        img_url=form.img_url.data,
        location=address,
        latitude=lat,
        longitude=lng,
        seats=form.seats.data,
        has_toilet=form.has_toilet.data,
        has_wifi=form.has_wifi.data,
        has_sockets=form.has_sockets.data,
        can_take_calls=form.can_take_calls.data,
        coffee_price=form.coffee_price.data,
    )


@web_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_cafe():
    """Handles adding a new cafe to the database.

    GET: Displays the add cafe form.
    POST: Processes the submitted form. Adds a new cafe if validation succeeds.
    Redirects to the index page upon successful addition or back to the add cafe form with validation errors.

    Returns:
        Response: The add cafe template on GET or redirect on successful POST.
    """
    form = CafeForm()
    if form.validate_on_submit():
        full_address = construct_full_address(form)
        latitude, longitude = get_geocode(full_address)

        if latitude is None or longitude is None:
            flash(
                "Address could not be geocoded. Please check the address details.",
                category='error',
            )
            return render_template("add_cafe.html", form=form)

        if cafe_exists(full_address):
            flash("Cafe already exists in the database.", category='error')
            return render_template("add_cafe.html", form=form)

        new_cafe = create_cafe(form, full_address, latitude, longitude)
        db.session.add(new_cafe)
        db.session.commit()
        flash("Successfully added the new cafe.", category='success')
        return redirect(url_for('web.home'))

    return render_template("add_cafe.html", form=form)


@web_blueprint.route('/delete-cafe/<int:cafe_id>')
@login_required
@admin_required
def delete_cafe(cafe_id):
    """Deletes a cafe from the database.

    Args:
        cafe_id (int): The ID of the cafe to delete.

    Returns:
        Response: Redirect to the index page.
    """
    cafe = db.session.get(Cafe, cafe_id)
    if cafe:
        db.session.delete(cafe)
        db.session.commit()
        flash("Cafe deleted successfully.", category='success')
    else:
        flash("Cafe not found.", category='error')
    return redirect(url_for('web.home'))

web/templates/add_cafe.html
{% extends "layout.html" %}
<!-- Page Title-->
{% block title %}Add Cafe{% endblock %}

<!-- Main Content -->
{% block content %}

<!-- Form Card -->
<div class="col-lg-6 col-md-12 add-cafe-form-section scrollable-section card">
	<form
		id="addCafeForm"
		method="post"
		action="{{ url_for('web.add_cafe') }}"
		class="card-body"
	>
		{{ form.hidden_tag() }}
		<div class="d-flex align-items-center mb-3">
			<span class="sb-title h5"
				><i class="fa-solid fa-map-location-dot"></i> Add a Cafe Location</span
			>
		</div>

		<!-- Form fields -->

		<!-- Name -->
		<div class="form-floating mb-3">
			{{ form.name(class="form-control" + (" is-invalid" if form.name.errors
			else ""), placeholder="Cafe Name") }}
			<label for="name">Cafe Name</label>
			{% if form.name.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.name.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- IMG URL -->
		<div class="form-floating mb-3">
			{{ form.img_url(class="form-control" + (" is-invalid" if
			form.img_url.errors else ""), placeholder="Image URL") }}
			<label for="img_url">Image URL</label>
			{% if form.img_url.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.img_url.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- Address -->
		<div class="form-floating mb-3">
			{{ form.location_input(class="form-control" + (" is-invalid" if
			form.location_input.errors else ""), placeholder="Address") }}
			<label for="location_input">Address</label>
			{% if form.location_input.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.location_input.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- ADDRESS 2 -->
		<div class="form-floating mb-3">
			{{ form.address2_input(class="form-control" + (" is-invalid" if
			form.address2_input.errors else ""), placeholder="Apt, Suite, etc
			(optional)") }}
			<label for="address2_input">Apt, Suite, etc (optional)</label>
			{% if form.address2_input.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.address2_input.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- City -->
		<div class="form-floating mb-3">
			{{ form.locality_input(class="form-control" + (" is-invalid" if
			form.locality_input.errors else ""), placeholder="City") }}
			<label for="locality_input">City</label>
			{% if form.locality_input.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.locality_input.errors[0] }}
			</div>
			{% endif %}
		</div>

		<div class="half-input-container mb-3">
			<!-- State/Province -->
			<div class="form-floating me-1">
				{{ form.administrative_area_level_1_input(class="form-control
				half-input" + (" is-invalid" if
				form.administrative_area_level_1_input.errors else ""),
				placeholder="State/Province") }}
				<label for="administrative_area_level_1_input">State/Province</label>
				{% if form.administrative_area_level_1_input.errors %}
				<div class="invalid-feedback" style="display: block">
					{{ form.administrative_area_level_1_input.errors[0] }}
				</div>
				{% endif %}
			</div>

			<!-- Zip/Postal code -->
			<div class="form-floating me-1">
				{{ form.postal_code_input(class="form-control half-input" + ("
				is-invalid" if form.postal_code_input.errors else ""),
				placeholder="Zip/Postal code") }}
				<label for="postal_code_input">Zip/Postal code</label>
				{% if form.postal_code_input.errors %}
				<div class="invalid-feedback" style="display: block">
					{{ form.postal_code_input.errors[0] }}
				</div>
				{% endif %}
			</div>
		</div>

		<!-- Country -->
		<div class="form-floating mb-3">
			{{ form.country_input(class="form-control" + (" is-invalid" if
			form.country_input.errors else ""), placeholder="Country") }}
			<label for="country_input">Country</label>
			{% if form.country_input.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.country_input.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- Boolean Fields -->
		<div class="boolean-input-container mb-3">
			<!-- Has Sockets -->
			<div class="form-check me-1">
				{{ form.has_sockets(class="form-check-input", id="has_sockets") }}
				<label class="form-check-label" for="has_sockets">Has Sockets?</label>
			</div>
			<!-- Has Toilet -->
			<div class="form-check me-1">
				{{ form.has_toilet(class="form-check-input", id="has_toilet") }}
				<label class="form-check-label" for="has_toilet">Has Toilet?</label>
			</div>
			<!-- Has Wifi -->
			<div class="form-check me-1">
				{{ form.has_wifi(class="form-check-input", id="has_wifi") }}
				<label class="form-check-label" for="has_wifi">Has Wi-Fi?</label>
			</div>
			<!-- Can Take Calls -->
			<div class="form-check me-1">
				{{ form.can_take_calls(class="form-check-input", id="can_take_calls") }}
				<label class="form-check-label" for="can_take_calls"
					>Can Take Calls?</label
				>
			</div>
		</div>

		<!-- Seat -->
		<div class="form-floating mb-3">
			{{ form.seats(class="form-control" + (" is-invalid" if form.seats.errors
			else ""), placeholder="Number of Seats") }}
			<label for="seats">Number of Seats</label>
			{% if form.seats.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.seats.errors[0] }}
			</div>
			{% endif %}
		</div>

		<!-- Coffee Price -->
		<div class="form-floating mb-3">
			{{ form.coffee_price(class="form-control" + (" is-invalid" if
			form.coffee_price.errors else ""), placeholder="Price of Coffee") }}
			<label for="coffee_price">Price of Coffee</label>
			{% if form.coffee_price.errors %}
			<div class="invalid-feedback" style="display: block">
				{{ form.coffee_price.errors[0] }}
			</div>
			{% endif %}
		</div>

		<br />
		{% with messages = get_flashed_messages(with_categories=true) %} {% if
		messages %} {% for category, message in messages %}
		<div
			class="alert {{ 'alert-success' if category == 'success' else 'alert-danger' }} alert-dismissible fade show text-center mb-3"
			role="alert"
		>
			{{ message }}
			<button
				type="button"
				class="btn-close"
				data-bs-dismiss="alert"
				aria-label="Close"
			></button>
		</div>
		{% endfor %} {% endif %} {% endwith %}

		<!-- Submit Button -->
		{{ form.submit(class="w-100 btn btn-lg btn-primary") }}
	</form>
</div>
<!-- Map -->
<div
	class="col-lg-6 col-md-12 scrollable-section map-container"
	id="gmp-map"
></div>

{% endblock %}

web/templates/home.html
{% extends "layout.html" %}
<!-- Page Title-->
{% block title %}Home{% endblock %}

<!-- Main Content -->
{% block content %}
<!-- Filter Sidebar Section -->
<div class="col-md-3 filter-sidebar">
	<!-- Accordion wrapper -->
	<div class="accordion" id="filterAccordion">
		<div class="accordion-item">
			<h2 class="accordion-header" id="headingFilters">
				<button
					class="accordion-button collapsed"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#collapseFilters"
					aria-expanded="false"
					aria-controls="collapseFilters"
				>
					FILTERS
				</button>
			</h2>
			<div
				id="collapseFilters"
				class="accordion-collapse collapse"
				aria-labelledby="headingFilters"
				data-bs-parent="#filterAccordion"
			>
				<div class="accordion-body">
					<!-- Filter icons -->
					<div class="my-3">
						<span
							id="has-wifi-icon"
							class="filter-icon"
							onclick="toggleFilter('has-wifi')"
							aria-label="Toggle Wi-Fi filter"
							><i class="fa-solid fa-wifi"></i
						></span>
						<span
							id="has-sockets-icon"
							class="filter-icon"
							onclick="toggleFilter('has-sockets')"
							aria-label="Toggle Sockets filter"
							><i class="fa-solid fa-plug"></i
						></span>
						<span
							id="has-toilet-icon"
							class="filter-icon"
							onclick="toggleFilter('has-toilet')"
							aria-label="Toggle Toilet filter"
							><i class="fa-solid fa-toilet"></i
						></span>
						<!-- Add more filter icons here -->
					</div>
					<hr />
					<!-- Additional filters -->
					<span
						id="can-take-calls-icon"
						class="filter-icon"
						onclick="toggleFilter('can-take-calls')"
						aria-label="Toggle Calls filter"
						><i class="fa-solid fa-phone-volume"></i
					></span>
					<!-- More filters can be added here -->
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Listing Section -->
<div class="col-md-6 listing-section">
	<div class="fixed-header">
		<h2 class="mt-3">Cafes</h2>
		<p>
			The best work and study-friendly cafes, restaurants, libraries, and hotel
			lobbies in the world.
		</p>
	</div>
	<div class="scrollable-list scrollable-section">
		<!-- Listings -->
		{% for cafe in cafes %}
		<div
			class="listing-card d-flex justify-content-between align-items-start mb-3"
			data-latitude="{{ cafe.latitude }}"
			data-longitude="{{ cafe.longitude }}"
			data-has-wifi="{{ cafe.has_wifi }}"
			data-has-sockets="{{ cafe.has_sockets }}"
			data-has-toilet="{{ cafe.has_toilet }}"
			data-can-take-calls="{{ cafe.can_take_calls }}"
			onclick="updateMapCenter(this)"
		>
			<img src="{{ cafe.img_url }}" alt="{{ cafe.name }}" class="img-fluid" />
			<div>
				<h3>{{ cafe.name|upper }}</h3>
				<p>{{ cafe.location }}</p>
			</div>
			<!-- Delete Button -->
			{% if current_user.is_admin %}
			<a href="{{ url_for('web.delete_cafe', cafe_id=cafe.id) }}" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete this cafe?');">
				<i class="fa-solid fa-trash"></i>
			</a>
			{% endif %}
		</div>
		{% endfor %}
	</div>
</div>

<!-- Map Section -->
<div class="col-md-3 map-container scrollable-section">
	<!-- Placeholder for Map Embedding (e.g., Google Earth API or iframe) -->
	{% if cafes and cafes|length > 0 %}
	<gmp-map
		id="cafemap"
		center="{{ cafes[0].latitude }},{{ cafes[0].longitude }}"
		zoom="16"
		map-id="MAP_ID"
	>
		{% for cafe in cafes %}
		<gmp-advanced-marker
			position="{{ cafe.latitude }},{{ cafe.longitude }}"
			title="{{ cafe.name }}"
			collisionBehavior="opt-in"
			gmpClickable="true"
		></gmp-advanced-marker>
		{% endfor %}
	</gmp-map>
	{% else %}
	<!-- Set to a default location, could be anywhere you'd prefer -->
	<gmp-map
		id="cafemap"
		center="48.8566,2.3522"
		zoom="16"
		map-id="MAP_ID"
	>
	</gmp-map>
	{% endif %}
</div>

{% endblock %}

web/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block head %}
		<title>{% block title %}{% endblock %} - Cafe & Wifi</title>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		{% block meta %}
		<meta name="description" content="Cafe & Wifi page" />
		<meta name="author" content="Brian Arriaga" />
		{% endblock meta %}
		<!-- Font Awesome icons (free version)-->
		<script
			src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
			crossorigin="anonymous"
		></script>
		<!-- Google fonts-->
		<link
			href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
			rel="stylesheet"
			type="text/css"
		/>
		<link
			rel="stylesheet"
			href="https://fonts.googleapis.com/css?family=Google+Sans+Text:500&amp;lang=en"
		/>
		<link
			href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
			rel="stylesheet"
			type="text/css"
		/>
		<!-- Bootstrap CSS -->
		{{ bootstrap.load_css() }}
		<!-- Core theme CSS -->
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='css/styles.css') }}"
		/>
		{% endblock %}
	</head>
	<body>
		<!-- Navigation-->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
			<div class="container-fluid px-4 px-lg-5">
				<a class="navbar-brand" href="{{ url_for('web.home') }}">Cafe & Wifi</a>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNav"
					aria-controls="navbarNav"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<i class="fa-solid fa-bars"></i>
				</button>
				<div class="collapse navbar-collapse bg-dark" id="navbarNav">
					<ul class="navbar-nav me-auto py-4 py-lg-0">
						<li class="nav-item active">
							<a class="nav-link" href="{{ url_for('web.home') }}">
								<i class="fa-solid fa-earth-americas"></i> ALL CITIES
							</a>
						</li>
						{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('web.add_cafe') }}"
								><i class="fa-solid fa-square-plus"></i> SUGGEST PLACES
							</a>
						</li>
						{% endif %}
					</ul>
					<ul class="navbar-nav">
						{% if not current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('web.register') }}">
								<i class="fa-solid fa-right-to-bracket"></i> JOIN COMMUNITY
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('web.login') }}">
								<i class="fa-solid fa-user"></i> LOGIN
							</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('web.logout') }}">
								<i class="fa-regular fa-square-caret-left"></i> LOGOUT
							</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>

		<!-- Content -->
		<div class="container-fluid content-container px-0 d-flex flex-column">
			<div class="row gx-0 flex-grow-1">
				<div class="container-fluid content-container d-flex h-100 px-0">
					{% block content %}{% endblock %}
				</div>
			</div>
		</div>

		<!-- Footer -->
		<footer class="bg-dark text-white text-center py-2 sticky-footer">
			<div class="container">
				<p class="mb-1">© 2024 Cafe & Wifi. All rights reserved.</p>
				<div>
					<a
						href="https://www.linkedin.com/in/brian-arriaga-s-28845b138/"
						class="text-white me-2"
						target="_blank"
						><i class="fa-brands fa-linkedin"></i
					></a>
					<a
						href="https://twitter.com/BAXTOR95"
						class="text-white me-2"
						target="_blank"
						><i class="fab fa-twitter"></i
					></a>
					<a
						href="https://github.com/BAXTOR95/"
						class="text-white me-2"
						target="_blank"
						><i class="fa-brands fa-github"></i
					></a>
				</div>
			</div>
		</footer>

		<!-- Bootstrap core JS-->
		{{ bootstrap.load_js() }}
		<!-- Core theme JS-->
		<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

		<!-- Google Maps -->
		<script
			src="https://maps.googleapis.com/maps/api/js?key={{ MAPS_API_KEY }}&libraries=maps,places,marker&callback=initApplication&solution_channel=GMP_QB_addressselection_v2_cABC&v=beta"
			async
			defer
		></script>
	</body>
</html>

web/templates/login.html
{% extends "layout.html" %}
<!-- Page Title-->
{% block title %}Login{% endblock %}

<!-- Main Content -->
{% block content %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6 col-lg-4 mt-2 mb-2">
			<form
				id="loginForm"
				method="post"
				action="{{ url_for('web.login') }}"
				class="p-4 p-md-3 border rounded-3 bg-light"
			>
				{{ form.hidden_tag() }}
				<div class="form-floating mb-3">
					{{ form.email(class="form-control" + (" is-invalid" if
					form.email.errors else ""), placeholder="name@example.com") }}
					<label for="email">Email address</label>
					{% if form.email.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.email.errors[0] }}
					</div>
					{% endif %}
				</div>
				<div class="form-floating mb-3">
					{{ form.password(class="form-control" + (" is-invalid" if
					form.password.errors else ""), placeholder="Enter your password...")
					}}
					<label for="password">Password</label>
					{% if form.password.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.password.errors[0] }}
					</div>
					{% endif %}
				</div>
				<br />
				{% with messages = get_flashed_messages(with_categories=true) %} {% if
				messages %} {% for category, message in messages %}
				<div
					class="alert {{ 'alert-success' if category == 'success' else 'alert-danger' }} alert-dismissible fade show text-center mb-3"
					role="alert"
				>
					{{ message }}
					<button
						type="button"
						class="btn-close"
						data-bs-dismiss="alert"
						aria-label="Close"
					></button>
				</div>
				{% endfor %} {% endif %} {% endwith %}
				<!-- Submit Button -->
				{{ form.submit(class="w-100 btn btn-lg btn-primary") }}
				<hr class="my-4" />
				<div class="text-center">
					<p class="text-muted">
						Don't have an account?
						<a href="{{ url_for('web.register') }}">Register here</a>
					</p>
				</div>
				<small class="text-muted"
					>By signing in, you agree to the terms of use.</small
				>
			</form>
		</div>
	</div>
</div>

{% endblock %}

web/templates/register.html
{% extends "layout.html" %}
<!-- Page Title-->
{% block title %}Register{% endblock %}

<!-- Main Content -->
{% block content %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6 col-lg-4 mt-2 mb-2">
			<form
				id="registerForm"
				method="post"
				action="{{ url_for('web.register') }}"
				class="p-4 p-md-3 border rounded-3 bg-light"
			>
				{{ form.hidden_tag() }}
				<div class="form-floating mb-3">
					{{ form.name(class="form-control" + (" is-invalid" if form.name.errors
					else ""), placeholder="Enter your name...") }}
					<label for="name">Full Name</label>
					{% if form.name.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.name.errors[0] }}
					</div>
					{% endif %}
				</div>
				<div class="form-floating mb-3">
					{{ form.email(class="form-control" + (" is-invalid" if
					form.email.errors else ""), placeholder="name@example.com") }}
					<label for="email">Email address</label>
					{% if form.email.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.email.errors[0] }}
					</div>
					{% endif %}
				</div>
				<div class="form-floating mb-3">
					{{ form.password(class="form-control" + (" is-invalid" if
					form.name.errors else ""), placeholder="Enter your password...") }}
					<label for="password">Password</label>
					{% if form.password.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.password.errors[0] }}
					</div>
					{% endif %}
				</div>
				<div class="form-floating mb-3">
					{{ form.password2(class="form-control" + (" is-invalid" if
					form.name.errors else ""), placeholder="Re-enter your password...") }}
					<label for="password2">Confirm Password</label>
					{% if form.password2.errors %}
					<div class="invalid-feedback" style="display: block">
						{{ form.password2.errors[0] }}
					</div>
					{% endif %}
				</div>
				<br />
				{% with messages = get_flashed_messages(with_categories=true) %} {% if
				messages %} {% for category, message in messages %}
				<div
					class="alert {{ 'alert-success' if category == 'success' else 'alert-danger' }} alert-dismissible fade show text-center mb-3"
					role="alert"
				>
					{{ message }}
					<button
						type="button"
						class="btn-close"
						data-bs-dismiss="alert"
						aria-label="Close"
					></button>
				</div>
				{% endfor %} {% endif %} {% endwith %}
				<!-- Submit Button -->
				{{ form.submit(class="w-100 btn btn-lg btn-primary") }}
				<hr class="my-4" />
				<div class="text-center">
					<p class="text-muted">
						Already have an account?
						<a href="{{ url_for('web.login') }}">Login here</a>
					</p>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}